name = "tg-file-host"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
DOMAIN = "your-domain.com"
USERNAME = "admin"
PASSWORD = "your-password"
ENABLE_AUTH = "true"
COOKIE = "7"
MAX_SIZE_MB = "20"
CHUNK_SIZE = "5242880"

[[d1_databases]]
binding = "DATABASE"
database_name = "imgbed"
database_id = "b3afe13f-d094-4bd3-a987-58ae918128e9"
